### PR TITLE
More typing, linting, docstrings, error handling

### PR DESCRIPTION
**Pull request by rlippmann**

### CODE REVIEW

**Comment by rsnodgrass** [comment]
Happy to merge. Cna you fix the branch conflicts with pyadtpulse/site.py?

**Comment by rlippmann** [comment]
Ok, resolved.

I have another change I'll be working on to see if I can get rid of the forced re-authorization.  I think it's just timing out.  So, I'll try doing a full refresh every 5 minutes.

**Comment by rsnodgrass** [comment]
Thanks!  I'll do a pypi package release once your next change is complete. If you could add any tests, that would be awesome (even just one or two).

**Comment by rlippmann** [comment]
> 

pytest tests?

Not sure what exactly to test since it requires login info…

**Pull request merged**
