### PR TITLE
Additional sensor detail

### PR DESCRIPTION
**Pull request by sbabcock23**
I noticed that my sensor types were not being picked up. During the analysis it looked like the name of the sensor was being relied on to determine the sensor type. I gathered the sensor detail by calling the device.jsp (if there is another way let me know). From there I retrieve the device type from ADT.

### CODE REVIEW

**Comment by rsnodgrass** [comment]
Thanks fo the contribution!!

**Comment by sbabcock23** [comment]
Hi @rsnodgrass ,

I do not see the latest changes in the pypi package. Would you be able to check?

Thanks!

**Comment by rsnodgrass** [comment]
It is there. Version 0.2.0
  
​
  
​​https://pypi.org/project/pyadtpulse/

**Comment by sbabcock23** [comment]
sorry @rsnodgrass, I downloaded the lasted version 0.2.0 but i do not see the changes in sites.py for example. Do you mind cross checking again please?

**Comment by rsnodgrass** [comment]
See 0.2.1, you are correct they did not get released.

**Pull request merged**
