### PR TITLE
pyadtpulse 1.1.1

### PR DESCRIPTION
**Pull request by rlippmann**
see changelog

### CODE REVIEW

**Comment by rlippmann** [comment]
@rsnodgrass I can't seem to get this uploaded to pypi.  I think the setup.py method is finally deprecated, and I have no idea how to change things to get it uploaded.

**Comment by rsnodgrass** [comment]
It must be on your side, I was just able to upload your latest 1.1.1.

https://pypi.org/project/pyadtpulse/1.1.1/

This is how I publish the latest from the command line:

```
python3 setup.py bdist_wheel
python3 -m twine upload dist/*
```

Not sure how you are updating PyPi?

**Comment by rsnodgrass** [comment]
Btw, we should probably switch to uploading to PyPi from your rlippmann@ fork instead of rsnodgrass/pyadtpulse.

**Comment by rlippmann** [comment]
That’s exactly how I did it.  Except I did twine instead of python3 -m twine

It worked for 1.1, so I’m not sure what the problem is.

I keep getting:

ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         Start filename for 'pyadtpulse' with 'pyadtpulse’.

Googling shows that the package upload system to pypi is somewhat broken right now.

I’m a newbie python programmer.  Is putting your main class in __init__.py not the recommended way anymore?

I’ve been trying to change that, and update the pyproject.toml, but the docs are really confusing.

On Oct 2, 2023, at 12:56 PM, Ryan ***@***.***> wrote:



It must be on your side, I was just able to upload your latest 1.1.1.

https://pypi.org/project/pyadtpulse/1.1.1/

This is how I publish the latest from the command line:

python3 setup.py bdist_wheel
python3 -m twine upload dist/*


Not sure how you are updating PyPi?

**Comment by rlippmann** [comment]
Do you want me to change the pyproject.toml to point to my GitHub for both projects?

On Oct 2, 2023, at 12:57 PM, Ryan ***@***.***> wrote:



Btw, we should probably switch to uploading to PyPi from your rlippmann@ fork instead of rsnodgrass/pyadtpulse.

**Comment by rsnodgrass** [comment]
That would be awesome! Thanks.

**Comment by rlippmann** [comment]
Ok, I don’t know why I can’t upload:

(default) ***@***.***:~/git/pyadtpulse$ python -m twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading pyadtpulse-1.1.2.linux-x86_64.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB • 00:00 • 199.9 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         Start filename for 'pyadtpulse' with 'pyadtpulse'.

(Verbose basically just shows me the html from pypi)

On Oct 4, 2023, at 8:00 PM, Ryan ***@***.***> wrote:


That would be awesome! Thanks.

**Comment by rlippmann** [comment]
Never mind. I was making an sdist too, and it was having problems

-- Rob

On Oct 4, 2023, at 8:00 PM, Ryan ***@***.***> wrote:

﻿

That would be awesome! Thanks.

**Comment by rlippmann** [comment]
Hey Ryan,

Think I could/should try and get this put into core?

Only issue is that I need full coverage for config flow in pytest, and I don’t know the first thing about pytest.

I think I've reverse engineered the 2fa flow, and was going to try to integrate it.  

— Rob

**Comment by rsnodgrass** [comment]
Your call! I don’t know the effort of adding to core.   
  

  
Thanks for all the updates and passion on improving this!
  
  
  
  
  
  
  

  
  
>

**Comment by rlippmann** [comment]
You’re welcome!

Do you still have pulse?  I thought you said you had moved to the home bridge version.

**Pull request merged**
